steps:
# AMD Build
- name: 'gcr.io/cloud-builders/docker'
  id: 'amd64'
  args:
  - 'build'
  - '-f=Dockerfile'
  - '--tag=gcr.io/${PROJECT_ID}/make-observation-psc:latest'
  - '.'
  waitFor: ['-']

# Push
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-amd64'
  args:
  - 'push'
  - 'gcr.io/${PROJECT_ID}/make-observation-psc:latest'
  waitFor: ['amd64']

images:
  - 'gcr.io/${PROJECT_ID}/make-observation-psc:latest'
