apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2020-03-26T16:50:46Z"
  generation: 5
  labels:
    app: plate-solver
  name: plate-solver
  namespace: panoptes-pipeline
  resourceVersion: "149977"
  selfLink: /apis/apps/v1/namespaces/panoptes-pipeline/deployments/plate-solver
  uid: 65866e99-6d9f-4b5a-b06d-08df417dc765
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: plate-solver
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: plate-solver
    spec:
      containers:
      - env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        image: gcr.io/panoptes-exp/plate-solve@sha256:feef88b2aa786402c06ea85513ac16901652ec0bd3a296bf06e8c50657b614c3
        imagePullPolicy: IfNotPresent
        name: plate-solve-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/secrets/google
          name: google-cloud-key
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: google-cloud-key
        secret:
          defaultMode: 420
          secretName: pipeline-key
status:
  conditions:
  - lastTransitionTime: "2020-03-26T17:23:07Z"
    lastUpdateTime: "2020-03-26T17:23:07Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2020-03-26T16:50:47Z"
    lastUpdateTime: "2020-03-26T17:40:41Z"
    message: ReplicaSet "plate-solver-6f855dd54d" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 5
  replicas: 3
  unavailableReplicas: 3
  updatedReplicas: 3
