apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-explorer
  name: data-explorer
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-explorer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: data-explorer
    spec:
      containers:
        - image: gcr.io/panoptes-exp/github.com/panoptes/panoptes-network
          imagePullPolicy: IfNotPresent
          name: data-explorer-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: data-explorer
  name: data-explorer-hpa-nhsr
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-explorer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-explorer
  name: data-explorer-service
  namespace: default
spec:
  clusterIP: 10.0.27.219
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 32598
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: data-explorer
  sessionAffinity: None
  type: NodePort
